### ISSUE TITLE
@vitejs/plugin-react can't detect preamble

### ISSUE THREAD

**Issue by dimitri-guitton** [santos-pierre/adonisjs-react-inertia#1]
Hello,

On my end, I also tried integrating Adonis with Inertia (React) and Vite. 
I spent quite some time on it and I'm facing the same error: `@vitejs/plugin-react can't detect preamble`
Have you found a solution on your side? 

Thanks in advance for your feedback.

**Comment by dimitri-guitton** [comment]
I found the solution thanks to this repository: [enzo-mir/adonis6_inertia](https://github.com/enzo-mir/adonis6_inertia)

You need to add `@viteReactRefresh()` In the root .edge file, in my case it looks like this

resources/views/app_root.edge
```html
<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="language" content="French">
  @viteReactRefresh()
  @vite(['resources/app.tsx'])
</head>

<body>
  @inertia()
</body>

</html>

```

**Comment by santos-pierre** [comment]
Hello @d-loki ,

Glad you found your solution. I also found it after asking a question on the Discord server. This repository was created to provide a way to reproduce the bug (my bad I didn't fix it here). Don't hesitate to join their Discord server to ask any questions; you'll receive quick and quality answers. Sometimes, it's even the core team that responds. Here is the [link to join](https://discord.com/invite/vDcEjq6).

Documentation for the inertia implementation will be available soon. 🤞

Have a nice day/evening!
